config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  namespace :admin do
    root to: 'organizations#index'
    resources :organizations, except: :show
  end

  scope :dashboard do
    scope module: 'user' do
      root 'users#dashboard', as: 'user_root'
      resources :users, only: [:index, :edit, :update]
      resources :menus, only: [:index, :show]
      resources :menu_items
      get 'orders', to: 'orders#index'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :category

  validates :name, :price, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :organization, optional: true
  has_many :orders

  before_create :organization_admin_exists?

  enum role: [:user, :admin]

  def organization_admin_exists?
    organization = self.organization
    self.role = User.where(organization_id: organization.id ).size == 0 ? 1 : 0
  end
end

app/controllers/user/menu_items_controller.rb
class User::MenuItemsController < DashboardController
  before_action :set_menu_item, except: [:index]

  def index; end

  def new;
    menu = Menu.find(params[:menu_id])
    @menu_categories = menu.categories
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)
    if @menu_item.save
      redirect_to menu_path(@menu_item.category.menu.id)
    else
      render :new
    end
  end

  def edit
    menu = Menu.find(params[:menu_id])
    @menu_categories = menu.categories
  end

  def update
    if @menu_item.update(menu_item_params)
      redirect_to menu_path(@menu_item.category.menu.id)
    else
      render :edit
    end
  end

  def destroy
    @menu_item.destroy
    redirect_to menu_path(@menu_item.category.menu.id)
  end

  private

  def menu_item_params
    params.require(:menu_item).permit(:name, :price, :category_id, :photo)
  end

  def set_menu_item
    @menu_item = MenuItem.find_or_initialize_by(id: params[:id])
  end
end

app/controllers/user/menus_controller.rb
class User::MenusController < DashboardController

  def index
    @menus = current_user.organization.menus
  end

  def show
    @result = Menu::Show.call(params: params)
    @menu = @result.menu
    @menu_categories = @result.menu_categories
  end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < DashboardController
  def index
    @total_sum = 0
    @orders = Order.all.map {|order| sum = order.order_items.map {|item| item.price}.sum; @total_sum += sum
      {order: order,
       list: order.order_items.group_by {|c| c.category}.map {|category, items| {category: category, items: items}},
       sum: sum,
      }
    }
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < DashboardController

  def index
    organization = current_user.organization
    @users = User.where(organization_id: organization.id).where.not(id: current_user.id)
  end

  def dashboard; end

  def calendar;  end

  def edit; end

  def update
    if old_password_wrong?
      redirect_back(fallback_location: root_path)
    elsif current_user.update(user_params)
      bypass_sign_in current_user
      redirect_to user_root_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def user_params
    permit_params = [:name, :organization_id, :email, :role]
    permit_params << [:password, :password_confirmation] if password_present?
    params.require(:user).permit(permit_params)
  end

  def password_present?
    params[:user][:password].present?
  end

  def old_password_wrong?
    return false unless password_present?
    !current_user.valid_password?(params[:user][:old_password])
  end

end

app/helpers/user/menu_items_helper.rb
module User::MenuItemsHelper
end

app/helpers/user/menus_helper.rb
module User::MenusHelper
end

app/helpers/user/orders_helper.rb
module User::OrdersHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/menu_items/_form.html.haml
= simple_form_for @menu_item, html: {role: 'form'} do |f|
  .card-body
    .form-group
      %label{for: "menu_item_name"} Name
      = f.input :name, placeholder: 'Enter name', input_html: {class: 'form-control'}, label: false
    .form-group
      %label{for: "menu_item_price"} Price
      = f.input :price, placeholder: 'Enter price', input_html: {class: 'form-control'}, label: false
    .form-group
      %label{for: "menu_item_category_id"} Choose category
      = f.input :category_id, collection: @menu_categories, input_html: {class: 'form-control'}, label: false ,include_blank: false
    .form-group
      %label{for: "menu_item_photo"} Photo
      = f.input :photo, as: :file, label: false, input_html: {class: 'form-control', id: 'menu_item_photo'}

  .card-footer
    = f.submit local_assigns[:btn_name], class: 'btn btn-success'

app/views/user/menu_items/edit.html.haml
.content
  .card.card-primary
    .card-header
      %h3.card-title Update Menu Item
    = render 'form', btn_name: 'Update'

app/views/user/menu_items/index.html.haml
%section.content
  = link_to 'Add', new_menu_item_path(menu_id: @menu), :class => 'btn btn-outline-primary mb-2'
  .card
    %ul
      - @menu_categories.each do |category|
        %li
          %h3= category.title.capitalize
          %table.table.table-bordered
            %thead
              %tr
                %th{:style => "width: 1%"}
                  \#
                %th{:style => "width: 20%"}
                  Name
                %th{:style => "width: 20%"}
                  Price
                %th{:style => "width: 20%"}
                  Photo
                %th{:style => "width: 10%"}
                  Actions

            %tbody
              - category.menu_items.each_with_index do |item, index|
                %tr
                  %td
                    = index + 1
                  %td
                    = item.name
                  %td
                    = item.price
                  %td
                    - unless item.photo.url.nil?
                      = image_tag item.photo.thumb.url
                  %td.project-actions.text-right
                    = link_to edit_menu_item_path(item,menu_id: @menu), class: 'btn btn-info btn-sm mr-1' do
                      %i.fas.fa-pencil-alt
                        Edit
                    = link_to menu_item_path(item), :method => 'delete', data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger' do
                      %i.fas.fa-trash
                        Delete

app/views/user/menu_items/new.html.haml
.content
  .card.card-primary
    .card-header
      %h3.card-title Create Menu Item
    = render 'form', btn_name: 'Create'