config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  namespace :admin do
    root to: 'organizations#index'
    resources :organizations, except: :show
  end

  scope :dashboard do
    scope module: 'user' do
      root 'users#dashboard', as: 'user_root'
      resources :users, only: [:index, :edit, :update]
      resources :menus, only: [:index, :show]
      resources :menu_items
      get 'orders', to: 'orders#index'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :menu
  has_many :menu_items

  validates :title, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :organization
  validates :name, presence: true
  has_many :categories
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :category

  validates :name, :price, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  def client_name
    self.user.name
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :category
  belongs_to :order

  validates :name, :price, presence: true
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users
  has_many :menus

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :organization, optional: true
  has_many :orders

  before_create :organization_admin_exists?

  enum role: [:user, :admin]

  def organization_admin_exists?
    organization = self.organization
    self.role = User.where(organization_id: organization.id ).size == 0 ? 1 : 0
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < Admin::AdminController
  before_action :set_organization, except: [:index]

  def index
    @organizations = Organization.all
  end

  def new; end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to admin_organizations_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @organization.update(organization_params)
      redirect_to admin_organizations_path
    else
      render :edit
    end
  end

  def destroy
    @organization.destroy
    redirect_to admin_organizations_path
  end

  private

  def organization_params
    params.require(:organization).permit(:name)
  end

  def set_organization
    @organization = Organization.find_or_initialize_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'
  #before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    if resource_class == User
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :organization_id,  :email, :password, :current_password])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :organization_id,:role, :email, :password, :current_password])
    else
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :current_password])
      devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :current_password])
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  # before_action :authenticate_user!

end

app/controllers/user/menus_controller.rb
class User::MenusController < DashboardController

  def index
    @menus = current_user.organization.menus
  end

  def show
    @result = Menu::Show.call(params: params)
    @menu = @result.menu
    @menu_categories = @result.menu_categories
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < DashboardController

  def index
    organization = current_user.organization
    @users = User.where(organization_id: organization.id).where.not(id: current_user.id)
  end

  def dashboard; end

  def calendar;  end

  def edit; end

  def update
    if old_password_wrong?
      redirect_back(fallback_location: root_path)
    elsif current_user.update(user_params)
      bypass_sign_in current_user
      redirect_to user_root_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def user_params
    permit_params = [:name, :organization_id, :email, :role]
    permit_params << [:password, :password_confirmation] if password_present?
    params.require(:user).permit(permit_params)
  end

  def password_present?
    params[:user][:password].present?
  end

  def old_password_wrong?
    return false unless password_present?
    !current_user.valid_password?(params[:user][:old_password])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	redirect_to user_root_path if current_user
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/menu_items_helper.rb
module User::MenuItemsHelper
end

app/helpers/user/menus_helper.rb
module User::MenusHelper
end

app/helpers/user/orders_helper.rb
module User::OrdersHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/organizations/_form.html.haml
%form{:role => "form"}
= simple_form_for [:admin, @organization] do |f|
  .card-body
    .form-group
      %label{:for => "organization_name"} Name
      = f.input :name, placeholder: 'Enter name', input_html: {class: 'form-control'}, label: false
    .form-group
  .card-footer
    = f.submit local_assigns[:btn_name], class: 'btn btn-success'

app/views/admin/organizations/_organization.html.haml
- organizations.each_with_index do | organization, index|
  %tr
    %td
      = index + 1
    %td
      = organization.name
    %td.project-actions.text-right
      = link_to edit_admin_organization_path(organization), class: 'btn btn-info btn-sm mr-1' do
        %i.fas.fa-pencil-alt
          Edit
      = link_to admin_organization_path(organization), :method => 'delete', data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger' do
        %i.fas.fa-trash
          Delete

app/views/admin/organizations/edit.html.haml
.content
  .card.card-primary
    .card-header
      %h3.card-title Edit Organization
    = render 'form', btn_name: 'Update'

app/views/admin/organizations/index.html.haml
%section.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        %h1 Organizations
  / /.container-fluid


%section.content
  = link_to 'Add', new_admin_organization_path, :class => 'btn btn-outline-primary mb-2'
  .card
    .card-header
      %h3.card-title Organizations
    .card-body.p-0
      %table.table.table-striped.projects
        %thead
          %tr
            %th{:style => "width: 1%"}
              \#
            %th{:style => "width: 20%"}
              Organization Name
            %th{:style => "width: 20%"}
        %tbody
          - @organizations.each_with_index do | organization, index|
            %tr
              %td
                = index + 1
              %td
                = organization.name
              %td.project-actions.text-right
                = link_to edit_admin_organization_path(organization), class: 'btn btn-info btn-sm mr-1' do
                  %i.fas.fa-pencil-alt
                    Edit
                = link_to admin_organization_path(organization), :method => 'delete', data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger' do
                  %i.fas.fa-trash
                    Delete

app/views/admin/organizations/new.html.haml
.content
  .card.card-primary
    .card-header
      %h3.card-title Create Organization
    = render 'form', btn_name: 'Create'