config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  namespace :admin do
    root to: 'organizations#index'
    resources :organizations, except: :show
  end

  scope :dashboard do
    scope module: 'user' do
      root 'users#dashboard', as: 'user_root'
      resources :users, only: [:index, :edit, :update]
      resources :menus, only: [:index, :show]
      resources :menu_items
      get 'orders', to: 'orders#index'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :organization, optional: true
  has_many :orders

  before_create :organization_admin_exists?

  enum role: [:user, :admin]

  def organization_admin_exists?
    organization = self.organization
    self.role = User.where(organization_id: organization.id ).size == 0 ? 1 : 0
  end
end

app/controllers/user/menu_items_controller.rb
class User::MenuItemsController < DashboardController
  before_action :set_menu_item, except: [:index]

  def index; end

  def new;
    menu = Menu.find(params[:menu_id])
    @menu_categories = menu.categories
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)
    if @menu_item.save
      redirect_to menu_path(@menu_item.category.menu.id)
    else
      render :new
    end
  end

  def edit
    menu = Menu.find(params[:menu_id])
    @menu_categories = menu.categories
  end

  def update
    if @menu_item.update(menu_item_params)
      redirect_to menu_path(@menu_item.category.menu.id)
    else
      render :edit
    end
  end

  def destroy
    @menu_item.destroy
    redirect_to menu_path(@menu_item.category.menu.id)
  end

  private

  def menu_item_params
    params.require(:menu_item).permit(:name, :price, :category_id, :photo)
  end

  def set_menu_item
    @menu_item = MenuItem.find_or_initialize_by(id: params[:id])
  end
end

app/controllers/user/menus_controller.rb
class User::MenusController < DashboardController

  def index
    @menus = current_user.organization.menus
  end

  def show
    @result = Menu::Show.call(params: params)
    @menu = @result.menu
    @menu_categories = @result.menu_categories
  end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < DashboardController
  def index
    @total_sum = 0
    @orders = Order.all.map {|order| sum = order.order_items.map {|item| item.price}.sum; @total_sum += sum
      {order: order,
       list: order.order_items.group_by {|c| c.category}.map {|category, items| {category: category, items: items}},
       sum: sum,
      }
    }
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < DashboardController

  def index
    organization = current_user.organization
    @users = User.where(organization_id: organization.id).where.not(id: current_user.id)
  end

  def dashboard; end

  def calendar;  end

  def edit; end

  def update
    if old_password_wrong?
      redirect_back(fallback_location: root_path)
    elsif current_user.update(user_params)
      bypass_sign_in current_user
      redirect_to user_root_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def user_params
    permit_params = [:name, :organization_id, :email, :role]
    permit_params << [:password, :password_confirmation] if password_present?
    params.require(:user).permit(permit_params)
  end

  def password_present?
    params[:user][:password].present?
  end

  def old_password_wrong?
    return false unless password_present?
    !current_user.valid_password?(params[:user][:old_password])
  end

end

app/helpers/user/menu_items_helper.rb
module User::MenuItemsHelper
end

app/helpers/user/menus_helper.rb
module User::MenusHelper
end

app/helpers/user/orders_helper.rb
module User::OrdersHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/layouts/user/_navbar.html.haml
/ Navbar
%nav.main-header.navbar.navbar-expand.navbar-white.navbar-light
  / Left navbar links
  %ul.navbar-nav
    %li.nav-item
      %a.nav-link{"data-widget" => "pushmenu", href: "#"}
        %i.fas.fa-bars
    %li.nav-item.d-none.d-sm-inline-block
      %a.nav-link{href: admin_root_path} Home
  / Right navbar links
  %ul.navbar-nav.ml-auto
    %li.nav-item
      = link_to destroy_admin_session_path, method: :delete, class: "nav-link" do
        %i.fas.fa-sign-out-alt

app/views/layouts/user/_sidebar.html.haml
/ Main Sidebar Container
%aside.main-sidebar.sidebar-dark-primary.elevation-4
  / Sidebar
  .sidebar
    / Sidebar user (optional)
    .user-panel.mt-3.pb-3.mb-3.d-flex
      .image
      .info
        %a.d-block{:href => edit_user_path(current_user)}
          = current_user.name
          %i.fas.fa-pencil-alt.ml-2

    / Sidebar Menu
    %nav.mt-2
      %ul.nav.nav-pills.nav-sidebar.flex-column{"data-accordion" => "false", "data-widget" => "treeview", :role => "menu"}
        %li.nav-item
          %a.nav-link{href: users_path }
            %i.nav-icon.far.fa-building
            %p Users
        %li.nav-item
          %a.nav-link{href: menus_path }
            %i.nav-icon.far.fa-bookmark
            %p Menus
        %li.nav-item
          %a.nav-link{href: orders_path }
            %i.nav-icon.far.fa-bookmark
            %p Orders
    / /.sidebar-menu
  / /.sidebar